//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\neomi.yehuda\Msc\קומפיילרים\CPQ\CPQ\Antlr\CPL.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CPQ.Antlr {
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using System.Collections.Generic;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public partial class CPLParser : Parser {
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, ADDOP=9, 
		AND=10, BREAK=11, CASE=12, CAST=13, DEFAULT=14, ELSE=15, FLOAT=16, IF=17, 
		INPUT=18, INT=19, OUTPUT=20, MULOP=21, NOT=22, OR=23, RELOP=24, SWITCH=25, 
		WHILE=26, ID=27, NUM=28, DELIMITED_COMMENT=29, WHITESPACES=30, SINGLE_LINE_COMMENT=31, 
		MULTILINE_COMMENT=32, SPACES=33;
	public const int
		RULE_program = 0, RULE_declarations = 1, RULE_declaration = 2, RULE_type = 3, 
		RULE_idlist = 4, RULE_stmt = 5, RULE_assignment_stmt = 6, RULE_input_stmt = 7, 
		RULE_output_stmt = 8, RULE_if_stmt = 9, RULE_while_stmt = 10, RULE_switch_stmt = 11, 
		RULE_caselist = 12, RULE_break_stmt = 13, RULE_stmt_block = 14, RULE_if_true_stmt = 15, 
		RULE_stmtlist = 16, RULE_boolexpr = 17, RULE_boolterm = 18, RULE_boolfactor = 19, 
		RULE_expression = 20, RULE_term = 21, RULE_factor = 22;
	public static readonly string[] ruleNames = {
		"program", "declarations", "declaration", "type", "idlist", "stmt", "assignment_stmt", 
		"input_stmt", "output_stmt", "if_stmt", "while_stmt", "switch_stmt", "caselist", 
		"break_stmt", "stmt_block", "if_true_stmt", "stmtlist", "boolexpr", "boolterm", 
		"boolfactor", "expression", "term", "factor"
	};

	private static readonly string[] _LiteralNames = {
		null, "':'", "';'", "','", "'='", "'('", "')'", "'{'", "'}'", null, "'&&'", 
		"'break'", "'case'", null, "'default'", "'else'", "'float'", "'if'", "'input'", 
		"'int'", "'output'", null, "'!'", "'||'", null, "'switch'", "'while'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, "ADDOP", "AND", 
		"BREAK", "CASE", "CAST", "DEFAULT", "ELSE", "FLOAT", "IF", "INPUT", "INT", 
		"OUTPUT", "MULOP", "NOT", "OR", "RELOP", "SWITCH", "WHILE", "ID", "NUM", 
		"DELIMITED_COMMENT", "WHITESPACES", "SINGLE_LINE_COMMENT", "MULTILINE_COMMENT", 
		"SPACES"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[System.Obsolete("Use Vocabulary instead.")]
	public static readonly string[] tokenNames = GenerateTokenNames(DefaultVocabulary, _SymbolicNames.Length);

	private static string[] GenerateTokenNames(IVocabulary vocabulary, int length) {
		string[] tokenNames = new string[length];
		for (int i = 0; i < tokenNames.Length; i++) {
			tokenNames[i] = vocabulary.GetLiteralName(i);
			if (tokenNames[i] == null) {
				tokenNames[i] = vocabulary.GetSymbolicName(i);
			}

			if (tokenNames[i] == null) {
				tokenNames[i] = "<INVALID>";
			}
		}

		return tokenNames;
	}

	[System.Obsolete("Use IRecognizer.Vocabulary instead.")]
	public override string[] TokenNames
	{
		get
		{
			return tokenNames;
		}
	}

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "CPL.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public CPLParser(ITokenStream input)
		: base(input)
	{
		_interp = new ParserATNSimulator(this,_ATN);
	}
	public partial class ProgramContext : ParserRuleContext {
		public DeclarationsContext declarations() {
			return GetRuleContext<DeclarationsContext>(0);
		}
		public Stmt_blockContext stmt_block() {
			return GetRuleContext<Stmt_blockContext>(0);
		}
		public ProgramContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_program; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterProgram(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitProgram(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgram(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgramContext program() {
		ProgramContext _localctx = new ProgramContext(_ctx, State);
		EnterRule(_localctx, 0, RULE_program);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 46; declarations(0);
			State = 47; stmt_block();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DeclarationsContext : ParserRuleContext {
		public DeclarationsContext declarations() {
			return GetRuleContext<DeclarationsContext>(0);
		}
		public DeclarationContext declaration() {
			return GetRuleContext<DeclarationContext>(0);
		}
		public DeclarationsContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_declarations; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterDeclarations(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitDeclarations(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDeclarations(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DeclarationsContext declarations() {
		return declarations(0);
	}

	private DeclarationsContext declarations(int _p) {
		ParserRuleContext _parentctx = _ctx;
		int _parentState = State;
		DeclarationsContext _localctx = new DeclarationsContext(_ctx, _parentState);
		DeclarationsContext _prevctx = _localctx;
		int _startState = 2;
		EnterRecursionRule(_localctx, 2, RULE_declarations, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			}
			_ctx.stop = _input.Lt(-1);
			State = 54;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,0,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( _parseListeners!=null ) TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new DeclarationsContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_declarations);
					State = 50;
					if (!(Precpred(_ctx, 2))) throw new FailedPredicateException(this, "Precpred(_ctx, 2)");
					State = 51; declaration();
					}
					} 
				}
				State = 56;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,0,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class DeclarationContext : ParserRuleContext {
		public IdlistContext idlist() {
			return GetRuleContext<IdlistContext>(0);
		}
		public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public DeclarationContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_declaration; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterDeclaration(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitDeclaration(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDeclaration(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DeclarationContext declaration() {
		DeclarationContext _localctx = new DeclarationContext(_ctx, State);
		EnterRule(_localctx, 4, RULE_declaration);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 57; idlist(0);
			State = 58; Match(T__0);
			State = 59; type();
			State = 60; Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContext : ParserRuleContext {
		public ITerminalNode INT() { return GetToken(CPLParser.INT, 0); }
		public ITerminalNode FLOAT() { return GetToken(CPLParser.FLOAT, 0); }
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterType(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitType(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeContext type() {
		TypeContext _localctx = new TypeContext(_ctx, State);
		EnterRule(_localctx, 6, RULE_type);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 62;
			_la = _input.La(1);
			if ( !(_la==FLOAT || _la==INT) ) {
			_errHandler.RecoverInline(this);
			} else {
				if (_input.La(1) == TokenConstants.Eof) {
					matchedEOF = true;
				}

				_errHandler.ReportMatch(this);
				Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdlistContext : ParserRuleContext {
		public IdlistContext idlist() {
			return GetRuleContext<IdlistContext>(0);
		}
		public ITerminalNode ID() { return GetToken(CPLParser.ID, 0); }
		public IdlistContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_idlist; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterIdlist(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitIdlist(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdlist(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdlistContext idlist() {
		return idlist(0);
	}

	private IdlistContext idlist(int _p) {
		ParserRuleContext _parentctx = _ctx;
		int _parentState = State;
		IdlistContext _localctx = new IdlistContext(_ctx, _parentState);
		IdlistContext _prevctx = _localctx;
		int _startState = 8;
		EnterRecursionRule(_localctx, 8, RULE_idlist, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 65; Match(ID);
			}
			_ctx.stop = _input.Lt(-1);
			State = 72;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,1,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( _parseListeners!=null ) TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new IdlistContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_idlist);
					State = 67;
					if (!(Precpred(_ctx, 2))) throw new FailedPredicateException(this, "Precpred(_ctx, 2)");
					State = 68; Match(T__2);
					State = 69; Match(ID);
					}
					} 
				}
				State = 74;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,1,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class StmtContext : ParserRuleContext {
		public Assignment_stmtContext assignment_stmt() {
			return GetRuleContext<Assignment_stmtContext>(0);
		}
		public Input_stmtContext input_stmt() {
			return GetRuleContext<Input_stmtContext>(0);
		}
		public Output_stmtContext output_stmt() {
			return GetRuleContext<Output_stmtContext>(0);
		}
		public If_stmtContext if_stmt() {
			return GetRuleContext<If_stmtContext>(0);
		}
		public While_stmtContext while_stmt() {
			return GetRuleContext<While_stmtContext>(0);
		}
		public Switch_stmtContext switch_stmt() {
			return GetRuleContext<Switch_stmtContext>(0);
		}
		public Break_stmtContext break_stmt() {
			return GetRuleContext<Break_stmtContext>(0);
		}
		public Stmt_blockContext stmt_block() {
			return GetRuleContext<Stmt_blockContext>(0);
		}
		public StmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterStmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitStmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StmtContext stmt() {
		StmtContext _localctx = new StmtContext(_ctx, State);
		EnterRule(_localctx, 10, RULE_stmt);
		try {
			State = 83;
			_errHandler.Sync(this);
			switch (_input.La(1)) {
			case ID:
				EnterOuterAlt(_localctx, 1);
				{
				State = 75; assignment_stmt();
				}
				break;
			case INPUT:
				EnterOuterAlt(_localctx, 2);
				{
				State = 76; input_stmt();
				}
				break;
			case OUTPUT:
				EnterOuterAlt(_localctx, 3);
				{
				State = 77; output_stmt();
				}
				break;
			case IF:
				EnterOuterAlt(_localctx, 4);
				{
				State = 78; if_stmt();
				}
				break;
			case WHILE:
				EnterOuterAlt(_localctx, 5);
				{
				State = 79; while_stmt();
				}
				break;
			case SWITCH:
				EnterOuterAlt(_localctx, 6);
				{
				State = 80; switch_stmt();
				}
				break;
			case BREAK:
				EnterOuterAlt(_localctx, 7);
				{
				State = 81; break_stmt();
				}
				break;
			case T__6:
				EnterOuterAlt(_localctx, 8);
				{
				State = 82; stmt_block();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Assignment_stmtContext : ParserRuleContext {
		public ITerminalNode ID() { return GetToken(CPLParser.ID, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Assignment_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assignment_stmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterAssignment_stmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitAssignment_stmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssignment_stmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Assignment_stmtContext assignment_stmt() {
		Assignment_stmtContext _localctx = new Assignment_stmtContext(_ctx, State);
		EnterRule(_localctx, 12, RULE_assignment_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 85; Match(ID);
			State = 86; Match(T__3);
			State = 87; expression(0);
			State = 88; Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Input_stmtContext : ParserRuleContext {
		public ITerminalNode INPUT() { return GetToken(CPLParser.INPUT, 0); }
		public ITerminalNode ID() { return GetToken(CPLParser.ID, 0); }
		public Input_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_input_stmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterInput_stmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitInput_stmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInput_stmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Input_stmtContext input_stmt() {
		Input_stmtContext _localctx = new Input_stmtContext(_ctx, State);
		EnterRule(_localctx, 14, RULE_input_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 90; Match(INPUT);
			State = 91; Match(T__4);
			State = 92; Match(ID);
			State = 93; Match(T__5);
			State = 94; Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Output_stmtContext : ParserRuleContext {
		public ITerminalNode OUTPUT() { return GetToken(CPLParser.OUTPUT, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Output_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_output_stmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterOutput_stmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitOutput_stmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOutput_stmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Output_stmtContext output_stmt() {
		Output_stmtContext _localctx = new Output_stmtContext(_ctx, State);
		EnterRule(_localctx, 16, RULE_output_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96; Match(OUTPUT);
			State = 97; Match(T__4);
			State = 98; expression(0);
			State = 99; Match(T__5);
			State = 100; Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class If_stmtContext : ParserRuleContext {
		public ITerminalNode IF() { return GetToken(CPLParser.IF, 0); }
		public BoolexprContext boolexpr() {
			return GetRuleContext<BoolexprContext>(0);
		}
		public If_true_stmtContext if_true_stmt() {
			return GetRuleContext<If_true_stmtContext>(0);
		}
		public ITerminalNode ELSE() { return GetToken(CPLParser.ELSE, 0); }
		public StmtContext stmt() {
			return GetRuleContext<StmtContext>(0);
		}
		public If_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_if_stmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterIf_stmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitIf_stmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIf_stmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public If_stmtContext if_stmt() {
		If_stmtContext _localctx = new If_stmtContext(_ctx, State);
		EnterRule(_localctx, 18, RULE_if_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 102; Match(IF);
			State = 103; Match(T__4);
			State = 104; boolexpr(0);
			State = 105; Match(T__5);
			State = 106; if_true_stmt();
			State = 107; Match(ELSE);
			State = 108; stmt();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class While_stmtContext : ParserRuleContext {
		public ITerminalNode WHILE() { return GetToken(CPLParser.WHILE, 0); }
		public BoolexprContext boolexpr() {
			return GetRuleContext<BoolexprContext>(0);
		}
		public StmtContext stmt() {
			return GetRuleContext<StmtContext>(0);
		}
		public While_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_while_stmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterWhile_stmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitWhile_stmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitWhile_stmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public While_stmtContext while_stmt() {
		While_stmtContext _localctx = new While_stmtContext(_ctx, State);
		EnterRule(_localctx, 20, RULE_while_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 110; Match(WHILE);
			State = 111; Match(T__4);
			State = 112; boolexpr(0);
			State = 113; Match(T__5);
			State = 114; stmt();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Switch_stmtContext : ParserRuleContext {
		public ITerminalNode SWITCH() { return GetToken(CPLParser.SWITCH, 0); }
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public CaselistContext caselist() {
			return GetRuleContext<CaselistContext>(0);
		}
		public ITerminalNode DEFAULT() { return GetToken(CPLParser.DEFAULT, 0); }
		public StmtlistContext stmtlist() {
			return GetRuleContext<StmtlistContext>(0);
		}
		public Switch_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_switch_stmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterSwitch_stmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitSwitch_stmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSwitch_stmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Switch_stmtContext switch_stmt() {
		Switch_stmtContext _localctx = new Switch_stmtContext(_ctx, State);
		EnterRule(_localctx, 22, RULE_switch_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 116; Match(SWITCH);
			State = 117; Match(T__4);
			State = 118; expression(0);
			State = 119; Match(T__5);
			State = 120; Match(T__6);
			State = 121; caselist(0);
			State = 122; Match(DEFAULT);
			State = 123; Match(T__0);
			State = 124; stmtlist(0);
			State = 125; Match(T__7);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CaselistContext : ParserRuleContext {
		public CaselistContext caselist() {
			return GetRuleContext<CaselistContext>(0);
		}
		public ITerminalNode CASE() { return GetToken(CPLParser.CASE, 0); }
		public ITerminalNode NUM() { return GetToken(CPLParser.NUM, 0); }
		public StmtlistContext stmtlist() {
			return GetRuleContext<StmtlistContext>(0);
		}
		public CaselistContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_caselist; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterCaselist(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitCaselist(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCaselist(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CaselistContext caselist() {
		return caselist(0);
	}

	private CaselistContext caselist(int _p) {
		ParserRuleContext _parentctx = _ctx;
		int _parentState = State;
		CaselistContext _localctx = new CaselistContext(_ctx, _parentState);
		CaselistContext _prevctx = _localctx;
		int _startState = 24;
		EnterRecursionRule(_localctx, 24, RULE_caselist, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			}
			_ctx.stop = _input.Lt(-1);
			State = 135;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,3,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( _parseListeners!=null ) TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new CaselistContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_caselist);
					State = 128;
					if (!(Precpred(_ctx, 2))) throw new FailedPredicateException(this, "Precpred(_ctx, 2)");
					State = 129; Match(CASE);
					State = 130; Match(NUM);
					State = 131; Match(T__0);
					State = 132; stmtlist(0);
					}
					} 
				}
				State = 137;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,3,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class Break_stmtContext : ParserRuleContext {
		public ITerminalNode BREAK() { return GetToken(CPLParser.BREAK, 0); }
		public Break_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_break_stmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterBreak_stmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitBreak_stmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBreak_stmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Break_stmtContext break_stmt() {
		Break_stmtContext _localctx = new Break_stmtContext(_ctx, State);
		EnterRule(_localctx, 26, RULE_break_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 138; Match(BREAK);
			State = 139; Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Stmt_blockContext : ParserRuleContext {
		public StmtlistContext stmtlist() {
			return GetRuleContext<StmtlistContext>(0);
		}
		public Stmt_blockContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmt_block; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterStmt_block(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitStmt_block(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStmt_block(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Stmt_blockContext stmt_block() {
		Stmt_blockContext _localctx = new Stmt_blockContext(_ctx, State);
		EnterRule(_localctx, 28, RULE_stmt_block);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 141; Match(T__6);
			State = 142; stmtlist(0);
			State = 143; Match(T__7);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class If_true_stmtContext : ParserRuleContext {
		public StmtContext stmt() {
			return GetRuleContext<StmtContext>(0);
		}
		public If_true_stmtContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_if_true_stmt; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterIf_true_stmt(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitIf_true_stmt(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIf_true_stmt(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public If_true_stmtContext if_true_stmt() {
		If_true_stmtContext _localctx = new If_true_stmtContext(_ctx, State);
		EnterRule(_localctx, 30, RULE_if_true_stmt);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 145; stmt();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StmtlistContext : ParserRuleContext {
		public StmtlistContext stmtlist() {
			return GetRuleContext<StmtlistContext>(0);
		}
		public StmtContext stmt() {
			return GetRuleContext<StmtContext>(0);
		}
		public StmtlistContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_stmtlist; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterStmtlist(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitStmtlist(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStmtlist(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StmtlistContext stmtlist() {
		return stmtlist(0);
	}

	private StmtlistContext stmtlist(int _p) {
		ParserRuleContext _parentctx = _ctx;
		int _parentState = State;
		StmtlistContext _localctx = new StmtlistContext(_ctx, _parentState);
		StmtlistContext _prevctx = _localctx;
		int _startState = 32;
		EnterRecursionRule(_localctx, 32, RULE_stmtlist, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			}
			_ctx.stop = _input.Lt(-1);
			State = 152;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,4,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( _parseListeners!=null ) TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new StmtlistContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_stmtlist);
					State = 148;
					if (!(Precpred(_ctx, 2))) throw new FailedPredicateException(this, "Precpred(_ctx, 2)");
					State = 149; stmt();
					}
					} 
				}
				State = 154;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,4,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class BoolexprContext : ParserRuleContext {
		public BoolexprContext boolexpr() {
			return GetRuleContext<BoolexprContext>(0);
		}
		public ITerminalNode OR() { return GetToken(CPLParser.OR, 0); }
		public BooltermContext boolterm() {
			return GetRuleContext<BooltermContext>(0);
		}
		public BoolexprContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_boolexpr; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterBoolexpr(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitBoolexpr(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBoolexpr(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BoolexprContext boolexpr() {
		return boolexpr(0);
	}

	private BoolexprContext boolexpr(int _p) {
		ParserRuleContext _parentctx = _ctx;
		int _parentState = State;
		BoolexprContext _localctx = new BoolexprContext(_ctx, _parentState);
		BoolexprContext _prevctx = _localctx;
		int _startState = 34;
		EnterRecursionRule(_localctx, 34, RULE_boolexpr, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 156; boolterm(0);
			}
			_ctx.stop = _input.Lt(-1);
			State = 163;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,5,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( _parseListeners!=null ) TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new BoolexprContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_boolexpr);
					State = 158;
					if (!(Precpred(_ctx, 2))) throw new FailedPredicateException(this, "Precpred(_ctx, 2)");
					State = 159; Match(OR);
					State = 160; boolterm(0);
					}
					} 
				}
				State = 165;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,5,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class BooltermContext : ParserRuleContext {
		public BooltermContext boolterm() {
			return GetRuleContext<BooltermContext>(0);
		}
		public ITerminalNode AND() { return GetToken(CPLParser.AND, 0); }
		public BoolfactorContext boolfactor() {
			return GetRuleContext<BoolfactorContext>(0);
		}
		public BooltermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_boolterm; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterBoolterm(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitBoolterm(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBoolterm(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BooltermContext boolterm() {
		return boolterm(0);
	}

	private BooltermContext boolterm(int _p) {
		ParserRuleContext _parentctx = _ctx;
		int _parentState = State;
		BooltermContext _localctx = new BooltermContext(_ctx, _parentState);
		BooltermContext _prevctx = _localctx;
		int _startState = 36;
		EnterRecursionRule(_localctx, 36, RULE_boolterm, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 167; boolfactor();
			}
			_ctx.stop = _input.Lt(-1);
			State = 174;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,6,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( _parseListeners!=null ) TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new BooltermContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_boolterm);
					State = 169;
					if (!(Precpred(_ctx, 2))) throw new FailedPredicateException(this, "Precpred(_ctx, 2)");
					State = 170; Match(AND);
					State = 171; boolfactor();
					}
					} 
				}
				State = 176;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,6,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class BoolfactorContext : ParserRuleContext {
		public ITerminalNode NOT() { return GetToken(CPLParser.NOT, 0); }
		public BoolexprContext boolexpr() {
			return GetRuleContext<BoolexprContext>(0);
		}
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ITerminalNode RELOP() { return GetToken(CPLParser.RELOP, 0); }
		public BoolfactorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_boolfactor; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterBoolfactor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitBoolfactor(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitBoolfactor(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public BoolfactorContext boolfactor() {
		BoolfactorContext _localctx = new BoolfactorContext(_ctx, State);
		EnterRule(_localctx, 38, RULE_boolfactor);
		try {
			State = 186;
			_errHandler.Sync(this);
			switch (_input.La(1)) {
			case NOT:
				EnterOuterAlt(_localctx, 1);
				{
				State = 177; Match(NOT);
				State = 178; Match(T__4);
				State = 179; boolexpr(0);
				State = 180; Match(T__5);
				}
				break;
			case T__4:
			case CAST:
			case ID:
			case NUM:
				EnterOuterAlt(_localctx, 2);
				{
				State = 182; expression(0);
				State = 183; Match(RELOP);
				State = 184; expression(0);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode ADDOP() { return GetToken(CPLParser.ADDOP, 0); }
		public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		return expression(0);
	}

	private ExpressionContext expression(int _p) {
		ParserRuleContext _parentctx = _ctx;
		int _parentState = State;
		ExpressionContext _localctx = new ExpressionContext(_ctx, _parentState);
		ExpressionContext _prevctx = _localctx;
		int _startState = 40;
		EnterRecursionRule(_localctx, 40, RULE_expression, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 189; term(0);
			}
			_ctx.stop = _input.Lt(-1);
			State = 196;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,8,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( _parseListeners!=null ) TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new ExpressionContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_expression);
					State = 191;
					if (!(Precpred(_ctx, 2))) throw new FailedPredicateException(this, "Precpred(_ctx, 2)");
					State = 192; Match(ADDOP);
					State = 193; term(0);
					}
					} 
				}
				State = 198;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,8,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class TermContext : ParserRuleContext {
		public TermContext term() {
			return GetRuleContext<TermContext>(0);
		}
		public ITerminalNode MULOP() { return GetToken(CPLParser.MULOP, 0); }
		public FactorContext factor() {
			return GetRuleContext<FactorContext>(0);
		}
		public TermContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_term; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterTerm(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitTerm(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTerm(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TermContext term() {
		return term(0);
	}

	private TermContext term(int _p) {
		ParserRuleContext _parentctx = _ctx;
		int _parentState = State;
		TermContext _localctx = new TermContext(_ctx, _parentState);
		TermContext _prevctx = _localctx;
		int _startState = 42;
		EnterRecursionRule(_localctx, 42, RULE_term, _p);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			{
			State = 200; factor();
			}
			_ctx.stop = _input.Lt(-1);
			State = 207;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,9,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					if ( _parseListeners!=null ) TriggerExitRuleEvent();
					_prevctx = _localctx;
					{
					{
					_localctx = new TermContext(_parentctx, _parentState);
					PushNewRecursionContext(_localctx, _startState, RULE_term);
					State = 202;
					if (!(Precpred(_ctx, 2))) throw new FailedPredicateException(this, "Precpred(_ctx, 2)");
					State = 203; Match(MULOP);
					State = 204; factor();
					}
					} 
				}
				State = 209;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,9,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			UnrollRecursionContexts(_parentctx);
		}
		return _localctx;
	}

	public partial class FactorContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public ITerminalNode CAST() { return GetToken(CPLParser.CAST, 0); }
		public ITerminalNode ID() { return GetToken(CPLParser.ID, 0); }
		public ITerminalNode NUM() { return GetToken(CPLParser.NUM, 0); }
		public FactorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_factor; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.EnterFactor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICPLListener typedListener = listener as ICPLListener;
			if (typedListener != null) typedListener.ExitFactor(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICPLVisitor<TResult> typedVisitor = visitor as ICPLVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFactor(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FactorContext factor() {
		FactorContext _localctx = new FactorContext(_ctx, State);
		EnterRule(_localctx, 44, RULE_factor);
		try {
			State = 221;
			_errHandler.Sync(this);
			switch (_input.La(1)) {
			case T__4:
				EnterOuterAlt(_localctx, 1);
				{
				State = 210; Match(T__4);
				State = 211; expression(0);
				State = 212; Match(T__5);
				}
				break;
			case CAST:
				EnterOuterAlt(_localctx, 2);
				{
				State = 214; Match(CAST);
				State = 215; Match(T__4);
				State = 216; expression(0);
				State = 217; Match(T__5);
				}
				break;
			case ID:
				EnterOuterAlt(_localctx, 3);
				{
				State = 219; Match(ID);
				}
				break;
			case NUM:
				EnterOuterAlt(_localctx, 4);
				{
				State = 220; Match(NUM);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public override bool Sempred(RuleContext _localctx, int ruleIndex, int predIndex) {
		switch (ruleIndex) {
		case 1: return declarations_sempred((DeclarationsContext)_localctx, predIndex);

		case 4: return idlist_sempred((IdlistContext)_localctx, predIndex);

		case 12: return caselist_sempred((CaselistContext)_localctx, predIndex);

		case 16: return stmtlist_sempred((StmtlistContext)_localctx, predIndex);

		case 17: return boolexpr_sempred((BoolexprContext)_localctx, predIndex);

		case 18: return boolterm_sempred((BooltermContext)_localctx, predIndex);

		case 20: return expression_sempred((ExpressionContext)_localctx, predIndex);

		case 21: return term_sempred((TermContext)_localctx, predIndex);
		}
		return true;
	}
	private bool declarations_sempred(DeclarationsContext _localctx, int predIndex) {
		switch (predIndex) {
		case 0: return Precpred(_ctx, 2);
		}
		return true;
	}
	private bool idlist_sempred(IdlistContext _localctx, int predIndex) {
		switch (predIndex) {
		case 1: return Precpred(_ctx, 2);
		}
		return true;
	}
	private bool caselist_sempred(CaselistContext _localctx, int predIndex) {
		switch (predIndex) {
		case 2: return Precpred(_ctx, 2);
		}
		return true;
	}
	private bool stmtlist_sempred(StmtlistContext _localctx, int predIndex) {
		switch (predIndex) {
		case 3: return Precpred(_ctx, 2);
		}
		return true;
	}
	private bool boolexpr_sempred(BoolexprContext _localctx, int predIndex) {
		switch (predIndex) {
		case 4: return Precpred(_ctx, 2);
		}
		return true;
	}
	private bool boolterm_sempred(BooltermContext _localctx, int predIndex) {
		switch (predIndex) {
		case 5: return Precpred(_ctx, 2);
		}
		return true;
	}
	private bool expression_sempred(ExpressionContext _localctx, int predIndex) {
		switch (predIndex) {
		case 6: return Precpred(_ctx, 2);
		}
		return true;
	}
	private bool term_sempred(TermContext _localctx, int predIndex) {
		switch (predIndex) {
		case 7: return Precpred(_ctx, 2);
		}
		return true;
	}

	public static readonly string _serializedATN =
		"\x3\xAF6F\x8320\x479D\xB75C\x4880\x1605\x191C\xAB37\x3#\xE2\x4\x2\t\x2"+
		"\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x4\t\t"+
		"\t\x4\n\t\n\x4\v\t\v\x4\f\t\f\x4\r\t\r\x4\xE\t\xE\x4\xF\t\xF\x4\x10\t"+
		"\x10\x4\x11\t\x11\x4\x12\t\x12\x4\x13\t\x13\x4\x14\t\x14\x4\x15\t\x15"+
		"\x4\x16\t\x16\x4\x17\t\x17\x4\x18\t\x18\x3\x2\x3\x2\x3\x2\x3\x3\x3\x3"+
		"\x3\x3\a\x3\x37\n\x3\f\x3\xE\x3:\v\x3\x3\x4\x3\x4\x3\x4\x3\x4\x3\x4\x3"+
		"\x5\x3\x5\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\x3\x6\a\x6I\n\x6\f\x6\xE\x6L\v"+
		"\x6\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x3\a\x5\aV\n\a\x3\b\x3\b\x3\b\x3"+
		"\b\x3\b\x3\t\x3\t\x3\t\x3\t\x3\t\x3\t\x3\n\x3\n\x3\n\x3\n\x3\n\x3\n\x3"+
		"\v\x3\v\x3\v\x3\v\x3\v\x3\v\x3\v\x3\v\x3\f\x3\f\x3\f\x3\f\x3\f\x3\f\x3"+
		"\r\x3\r\x3\r\x3\r\x3\r\x3\r\x3\r\x3\r\x3\r\x3\r\x3\r\x3\xE\x3\xE\x3\xE"+
		"\x3\xE\x3\xE\x3\xE\a\xE\x88\n\xE\f\xE\xE\xE\x8B\v\xE\x3\xF\x3\xF\x3\xF"+
		"\x3\x10\x3\x10\x3\x10\x3\x10\x3\x11\x3\x11\x3\x12\x3\x12\x3\x12\a\x12"+
		"\x99\n\x12\f\x12\xE\x12\x9C\v\x12\x3\x13\x3\x13\x3\x13\x3\x13\x3\x13\x3"+
		"\x13\a\x13\xA4\n\x13\f\x13\xE\x13\xA7\v\x13\x3\x14\x3\x14\x3\x14\x3\x14"+
		"\x3\x14\x3\x14\a\x14\xAF\n\x14\f\x14\xE\x14\xB2\v\x14\x3\x15\x3\x15\x3"+
		"\x15\x3\x15\x3\x15\x3\x15\x3\x15\x3\x15\x3\x15\x5\x15\xBD\n\x15\x3\x16"+
		"\x3\x16\x3\x16\x3\x16\x3\x16\x3\x16\a\x16\xC5\n\x16\f\x16\xE\x16\xC8\v"+
		"\x16\x3\x17\x3\x17\x3\x17\x3\x17\x3\x17\x3\x17\a\x17\xD0\n\x17\f\x17\xE"+
		"\x17\xD3\v\x17\x3\x18\x3\x18\x3\x18\x3\x18\x3\x18\x3\x18\x3\x18\x3\x18"+
		"\x3\x18\x3\x18\x3\x18\x5\x18\xE0\n\x18\x3\x18\x2\x2\n\x4\n\x1A\"$&*,\x19"+
		"\x2\x2\x4\x2\x6\x2\b\x2\n\x2\f\x2\xE\x2\x10\x2\x12\x2\x14\x2\x16\x2\x18"+
		"\x2\x1A\x2\x1C\x2\x1E\x2 \x2\"\x2$\x2&\x2(\x2*\x2,\x2.\x2\x2\x3\x4\x2"+
		"\x12\x12\x15\x15\xDD\x2\x30\x3\x2\x2\x2\x4\x33\x3\x2\x2\x2\x6;\x3\x2\x2"+
		"\x2\b@\x3\x2\x2\x2\n\x42\x3\x2\x2\x2\fU\x3\x2\x2\x2\xEW\x3\x2\x2\x2\x10"+
		"\\\x3\x2\x2\x2\x12\x62\x3\x2\x2\x2\x14h\x3\x2\x2\x2\x16p\x3\x2\x2\x2\x18"+
		"v\x3\x2\x2\x2\x1A\x81\x3\x2\x2\x2\x1C\x8C\x3\x2\x2\x2\x1E\x8F\x3\x2\x2"+
		"\x2 \x93\x3\x2\x2\x2\"\x95\x3\x2\x2\x2$\x9D\x3\x2\x2\x2&\xA8\x3\x2\x2"+
		"\x2(\xBC\x3\x2\x2\x2*\xBE\x3\x2\x2\x2,\xC9\x3\x2\x2\x2.\xDF\x3\x2\x2\x2"+
		"\x30\x31\x5\x4\x3\x2\x31\x32\x5\x1E\x10\x2\x32\x3\x3\x2\x2\x2\x33\x38"+
		"\b\x3\x1\x2\x34\x35\f\x4\x2\x2\x35\x37\x5\x6\x4\x2\x36\x34\x3\x2\x2\x2"+
		"\x37:\x3\x2\x2\x2\x38\x36\x3\x2\x2\x2\x38\x39\x3\x2\x2\x2\x39\x5\x3\x2"+
		"\x2\x2:\x38\x3\x2\x2\x2;<\x5\n\x6\x2<=\a\x3\x2\x2=>\x5\b\x5\x2>?\a\x4"+
		"\x2\x2?\a\x3\x2\x2\x2@\x41\t\x2\x2\x2\x41\t\x3\x2\x2\x2\x42\x43\b\x6\x1"+
		"\x2\x43\x44\a\x1D\x2\x2\x44J\x3\x2\x2\x2\x45\x46\f\x4\x2\x2\x46G\a\x5"+
		"\x2\x2GI\a\x1D\x2\x2H\x45\x3\x2\x2\x2IL\x3\x2\x2\x2JH\x3\x2\x2\x2JK\x3"+
		"\x2\x2\x2K\v\x3\x2\x2\x2LJ\x3\x2\x2\x2MV\x5\xE\b\x2NV\x5\x10\t\x2OV\x5"+
		"\x12\n\x2PV\x5\x14\v\x2QV\x5\x16\f\x2RV\x5\x18\r\x2SV\x5\x1C\xF\x2TV\x5"+
		"\x1E\x10\x2UM\x3\x2\x2\x2UN\x3\x2\x2\x2UO\x3\x2\x2\x2UP\x3\x2\x2\x2UQ"+
		"\x3\x2\x2\x2UR\x3\x2\x2\x2US\x3\x2\x2\x2UT\x3\x2\x2\x2V\r\x3\x2\x2\x2"+
		"WX\a\x1D\x2\x2XY\a\x6\x2\x2YZ\x5*\x16\x2Z[\a\x4\x2\x2[\xF\x3\x2\x2\x2"+
		"\\]\a\x14\x2\x2]^\a\a\x2\x2^_\a\x1D\x2\x2_`\a\b\x2\x2`\x61\a\x4\x2\x2"+
		"\x61\x11\x3\x2\x2\x2\x62\x63\a\x16\x2\x2\x63\x64\a\a\x2\x2\x64\x65\x5"+
		"*\x16\x2\x65\x66\a\b\x2\x2\x66g\a\x4\x2\x2g\x13\x3\x2\x2\x2hi\a\x13\x2"+
		"\x2ij\a\a\x2\x2jk\x5$\x13\x2kl\a\b\x2\x2lm\x5 \x11\x2mn\a\x11\x2\x2no"+
		"\x5\f\a\x2o\x15\x3\x2\x2\x2pq\a\x1C\x2\x2qr\a\a\x2\x2rs\x5$\x13\x2st\a"+
		"\b\x2\x2tu\x5\f\a\x2u\x17\x3\x2\x2\x2vw\a\x1B\x2\x2wx\a\a\x2\x2xy\x5*"+
		"\x16\x2yz\a\b\x2\x2z{\a\t\x2\x2{|\x5\x1A\xE\x2|}\a\x10\x2\x2}~\a\x3\x2"+
		"\x2~\x7F\x5\"\x12\x2\x7F\x80\a\n\x2\x2\x80\x19\x3\x2\x2\x2\x81\x89\b\xE"+
		"\x1\x2\x82\x83\f\x4\x2\x2\x83\x84\a\xE\x2\x2\x84\x85\a\x1E\x2\x2\x85\x86"+
		"\a\x3\x2\x2\x86\x88\x5\"\x12\x2\x87\x82\x3\x2\x2\x2\x88\x8B\x3\x2\x2\x2"+
		"\x89\x87\x3\x2\x2\x2\x89\x8A\x3\x2\x2\x2\x8A\x1B\x3\x2\x2\x2\x8B\x89\x3"+
		"\x2\x2\x2\x8C\x8D\a\r\x2\x2\x8D\x8E\a\x4\x2\x2\x8E\x1D\x3\x2\x2\x2\x8F"+
		"\x90\a\t\x2\x2\x90\x91\x5\"\x12\x2\x91\x92\a\n\x2\x2\x92\x1F\x3\x2\x2"+
		"\x2\x93\x94\x5\f\a\x2\x94!\x3\x2\x2\x2\x95\x9A\b\x12\x1\x2\x96\x97\f\x4"+
		"\x2\x2\x97\x99\x5\f\a\x2\x98\x96\x3\x2\x2\x2\x99\x9C\x3\x2\x2\x2\x9A\x98"+
		"\x3\x2\x2\x2\x9A\x9B\x3\x2\x2\x2\x9B#\x3\x2\x2\x2\x9C\x9A\x3\x2\x2\x2"+
		"\x9D\x9E\b\x13\x1\x2\x9E\x9F\x5&\x14\x2\x9F\xA5\x3\x2\x2\x2\xA0\xA1\f"+
		"\x4\x2\x2\xA1\xA2\a\x19\x2\x2\xA2\xA4\x5&\x14\x2\xA3\xA0\x3\x2\x2\x2\xA4"+
		"\xA7\x3\x2\x2\x2\xA5\xA3\x3\x2\x2\x2\xA5\xA6\x3\x2\x2\x2\xA6%\x3\x2\x2"+
		"\x2\xA7\xA5\x3\x2\x2\x2\xA8\xA9\b\x14\x1\x2\xA9\xAA\x5(\x15\x2\xAA\xB0"+
		"\x3\x2\x2\x2\xAB\xAC\f\x4\x2\x2\xAC\xAD\a\f\x2\x2\xAD\xAF\x5(\x15\x2\xAE"+
		"\xAB\x3\x2\x2\x2\xAF\xB2\x3\x2\x2\x2\xB0\xAE\x3\x2\x2\x2\xB0\xB1\x3\x2"+
		"\x2\x2\xB1\'\x3\x2\x2\x2\xB2\xB0\x3\x2\x2\x2\xB3\xB4\a\x18\x2\x2\xB4\xB5"+
		"\a\a\x2\x2\xB5\xB6\x5$\x13\x2\xB6\xB7\a\b\x2\x2\xB7\xBD\x3\x2\x2\x2\xB8"+
		"\xB9\x5*\x16\x2\xB9\xBA\a\x1A\x2\x2\xBA\xBB\x5*\x16\x2\xBB\xBD\x3\x2\x2"+
		"\x2\xBC\xB3\x3\x2\x2\x2\xBC\xB8\x3\x2\x2\x2\xBD)\x3\x2\x2\x2\xBE\xBF\b"+
		"\x16\x1\x2\xBF\xC0\x5,\x17\x2\xC0\xC6\x3\x2\x2\x2\xC1\xC2\f\x4\x2\x2\xC2"+
		"\xC3\a\v\x2\x2\xC3\xC5\x5,\x17\x2\xC4\xC1\x3\x2\x2\x2\xC5\xC8\x3\x2\x2"+
		"\x2\xC6\xC4\x3\x2\x2\x2\xC6\xC7\x3\x2\x2\x2\xC7+\x3\x2\x2\x2\xC8\xC6\x3"+
		"\x2\x2\x2\xC9\xCA\b\x17\x1\x2\xCA\xCB\x5.\x18\x2\xCB\xD1\x3\x2\x2\x2\xCC"+
		"\xCD\f\x4\x2\x2\xCD\xCE\a\x17\x2\x2\xCE\xD0\x5.\x18\x2\xCF\xCC\x3\x2\x2"+
		"\x2\xD0\xD3\x3\x2\x2\x2\xD1\xCF\x3\x2\x2\x2\xD1\xD2\x3\x2\x2\x2\xD2-\x3"+
		"\x2\x2\x2\xD3\xD1\x3\x2\x2\x2\xD4\xD5\a\a\x2\x2\xD5\xD6\x5*\x16\x2\xD6"+
		"\xD7\a\b\x2\x2\xD7\xE0\x3\x2\x2\x2\xD8\xD9\a\xF\x2\x2\xD9\xDA\a\a\x2\x2"+
		"\xDA\xDB\x5*\x16\x2\xDB\xDC\a\b\x2\x2\xDC\xE0\x3\x2\x2\x2\xDD\xE0\a\x1D"+
		"\x2\x2\xDE\xE0\a\x1E\x2\x2\xDF\xD4\x3\x2\x2\x2\xDF\xD8\x3\x2\x2\x2\xDF"+
		"\xDD\x3\x2\x2\x2\xDF\xDE\x3\x2\x2\x2\xE0/\x3\x2\x2\x2\r\x38JU\x89\x9A"+
		"\xA5\xB0\xBC\xC6\xD1\xDF";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
} // namespace CPQ.Antlr
