//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\neomi.yehuda\Msc\Compilers\CPQ\src\CPQ\Antlr\CPL.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CPQ {

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICPLListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public partial class CPLBaseListener : ICPLListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] CPLParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] CPLParser.ProgramContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.declarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarations([NotNull] CPLParser.DeclarationsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.declarations"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarations([NotNull] CPLParser.DeclarationsContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] CPLParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] CPLParser.DeclarationContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] CPLParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] CPLParser.TypeContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.idlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdlist([NotNull] CPLParser.IdlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.idlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdlist([NotNull] CPLParser.IdlistContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt([NotNull] CPLParser.StmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt([NotNull] CPLParser.StmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.assignment_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment_stmt([NotNull] CPLParser.Assignment_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.assignment_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment_stmt([NotNull] CPLParser.Assignment_stmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.input_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInput_stmt([NotNull] CPLParser.Input_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.input_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInput_stmt([NotNull] CPLParser.Input_stmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.output_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOutput_stmt([NotNull] CPLParser.Output_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.output_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOutput_stmt([NotNull] CPLParser.Output_stmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.if_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIf_stmt([NotNull] CPLParser.If_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.if_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIf_stmt([NotNull] CPLParser.If_stmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.while_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhile_stmt([NotNull] CPLParser.While_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.while_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhile_stmt([NotNull] CPLParser.While_stmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.switch_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSwitch_stmt([NotNull] CPLParser.Switch_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.switch_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSwitch_stmt([NotNull] CPLParser.Switch_stmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.caselist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCaselist([NotNull] CPLParser.CaselistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.caselist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCaselist([NotNull] CPLParser.CaselistContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.break_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreak_stmt([NotNull] CPLParser.Break_stmtContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.break_stmt"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreak_stmt([NotNull] CPLParser.Break_stmtContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.stmt_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmt_block([NotNull] CPLParser.Stmt_blockContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.stmt_block"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmt_block([NotNull] CPLParser.Stmt_blockContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.stmtlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStmtlist([NotNull] CPLParser.StmtlistContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.stmtlist"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStmtlist([NotNull] CPLParser.StmtlistContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.boolexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolexpr([NotNull] CPLParser.BoolexprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.boolexpr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolexpr([NotNull] CPLParser.BoolexprContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.boolterm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolterm([NotNull] CPLParser.BooltermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.boolterm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolterm([NotNull] CPLParser.BooltermContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.boolfactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolfactor([NotNull] CPLParser.BoolfactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.boolfactor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolfactor([NotNull] CPLParser.BoolfactorContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] CPLParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] CPLParser.ExpressionContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTerm([NotNull] CPLParser.TermContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.term"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTerm([NotNull] CPLParser.TermContext context) { }

	/// <summary>
	/// Enter a parse tree produced by <see cref="CPLParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] CPLParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CPLParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] CPLParser.FactorContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace CPQ
