//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\neomi.yehuda\Msc\Compilers\CPQ\src\CPQ\Antlr\CPL.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace CPQ {
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CPLParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public interface ICPLVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] CPLParser.ProgramContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarations([NotNull] CPLParser.DeclarationsContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] CPLParser.DeclarationContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] CPLParser.TypeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.idlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdlist([NotNull] CPLParser.IdlistContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmt([NotNull] CPLParser.StmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.assignment_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_stmt([NotNull] CPLParser.Assignment_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.input_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInput_stmt([NotNull] CPLParser.Input_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.output_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOutput_stmt([NotNull] CPLParser.Output_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.if_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIf_stmt([NotNull] CPLParser.If_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.while_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhile_stmt([NotNull] CPLParser.While_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.switch_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_stmt([NotNull] CPLParser.Switch_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.caselist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCaselist([NotNull] CPLParser.CaselistContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.break_stmt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreak_stmt([NotNull] CPLParser.Break_stmtContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.stmt_block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmt_block([NotNull] CPLParser.Stmt_blockContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.stmtlist"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStmtlist([NotNull] CPLParser.StmtlistContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.boolexpr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolexpr([NotNull] CPLParser.BoolexprContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.boolterm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolterm([NotNull] CPLParser.BooltermContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.boolfactor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolfactor([NotNull] CPLParser.BoolfactorContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] CPLParser.ExpressionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.term"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTerm([NotNull] CPLParser.TermContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CPLParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] CPLParser.FactorContext context);
}
} // namespace CPQ
